# Generated by Django 3.1 on 2020-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'seceondary'), ('d', 'danger')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('s', 'Shirt'), ('sw', 'sportsWear'), ('ow', 'outWear')], max_length=2),
        ),
    ]
