# Generated by Django 3.1 on 2020-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('s', 'Shirt'), ('sw', 'sportsWear'), ('ow', 'outWear'), ('bw', 'bottomwear')], max_length=2),
        ),
    ]
