# Generated by Django 3.1 on 2020-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201203_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='set-products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('d', 'danger')], max_length=1),
        ),
    ]
