# Generated by Django 3.1 on 2020-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descrption',
            field=models.TextField(default='this is test description something somwthing '),
            preserve_default=False,
        ),
    ]
