# Generated by Django 3.1 on 2020-12-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderd_date',
            new_name='ordered_date',
        ),
    ]
