# Generated by Django 3.1.7 on 2021-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210502_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
