# Generated by Django 3.1.7 on 2021-05-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billlingAddress',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('S', 'shipping'), ('B', 'billing')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='billling_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billling_address', to='core.billingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='core.billingaddress'),
        ),
    ]
