# Generated by Django 3.1.7 on 2021-05-10 19:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210504_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'BillingAddresses'},
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
